// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcihodnumirjsrwkynek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaWhvZG51bWlyanNyd2t5bmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzQzOTMsImV4cCI6MjA3NDE1MDM5M30.0l_fU-lDsCUzRdjTHEouEHwQFJ6apKMYx66MXAlY2Kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});